service: hello-world-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: ${opt:stage, 'dev'}

functions:
  api:
    handler: main.handler
    name: ${self:provider.stage}-hello-world
    description: Hello World API with FastAPI

package:
  patterns:
    - "**/*"
    - "!node_modules/**"
    - "!venv/**"
    - "!.env"
    - "!.env.example"
    - "!.git/**"
    - "!.github/**"
    - "!.terraform/**"
    - "!environments/**"
    - "!modules/**"

# This tells Serverless not to attempt to create/update these resources
resources:
  Resources:
    # Tell Serverless to skip creating the CloudWatch log group
    ApiLogGroup:
      Type: "AWS::Logs::LogGroup"
      Properties:
        LogGroupName: "/aws/lambda/${self:provider.stage}-hello-world"
      DeletionPolicy: Retain
      # This is the key part - it tells Serverless this resource already exists
      DependsOn: "ServerlessSkipResourceCreationMarker"

    # This is a dummy resource that doesn't create anything
    ServerlessSkipResourceCreationMarker:
      Type: "Custom::SkipCreation"

  # Explicitly tell Serverless not to remove resources on updates/removal
  Outputs:
    ServerlessSkipResourceRemovalOutput:
      Value: "This helps Serverless skip resource removal"
