service: hello-world-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: ${opt:stage, 'dev'}

functions:
  api:
    handler: main.handler
    name: ${self:provider.stage}-hello-world
    description: Hello World API with FastAPI

package:
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!.env"
    - "!.env.example"
    - "!.git/**"
    - "!.github/**"
    - "!.terraform/**"
    - "!environments/**"
    - "!modules/**"
