name: Deploy to AWS Lambda via Serverless

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            npm run deploy:dev
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            npm run deploy:stage
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            npm run deploy:prod
          fi
